/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Roles.CustomerRole;
import Business.Roles.InvestorRole;
import Business.UserAccount.UserAccount;
import com.teknikindustries.bulksms.SMS;
import java.awt.CardLayout;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Niyati Maheshwari
 */
public class SignUpFormJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpFormJPanel
     */
    private JPanel viewJPanel;
    private EcoSystem business;
    private OrganizationDirectory organizationDirectory;
    private Enterprise enterprise;
    private String email;
    private String name;
    private String username;
    private String password;
    private long mobileNumber;

    public SignUpFormJPanel(JPanel viewJPanel, EcoSystem system) {
        initComponents();
        this.viewJPanel = viewJPanel;
        this.business = system;
    }

    public void Textfields() {
        nameTextField.setText("");
        emailIdTextField.setText("");
        usernameTextField.setText("");
        passwordTextField.setText("");
        mobileNumTextField.setText("");
        RoleCombobox.setSelectedIndex(0);
    }

    public void mail() {
        SMS sms= new SMS();
        sms.SendSMS("Niymahes", "mavericks", "Hi Welcome to mavericks system","+1"+mobileNumTextField.getText() , "http://usa.bulksms.com/eapi/submission/send_sms/2/2.0");
        JOptionPane.showMessageDialog(null, "Message sent!");
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", "465");

        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication("acharya.rupesh0@gmail.com", "dishaclasses");
            }
        }
        );
        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("acharya.rupesh0@gmail.com"));
            System.out.print(email);
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(email));
            message.setSubject("Welcome to the mavericks project");
            message.setText("Hi new sign up done successfully");
            Transport.send(message);
            JOptionPane.showMessageDialog(null, "Mail is sent");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingJLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        RoleLabel = new javax.swing.JLabel();
        RoleCombobox = new javax.swing.JComboBox();
        nameJLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        emailJLabel = new javax.swing.JLabel();
        emailIdTextField = new javax.swing.JTextField();
        mobileNumJLabel = new javax.swing.JLabel();
        mobileNumTextField = new javax.swing.JTextField();
        usernameJLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordJLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        signUpButton = new javax.swing.JButton();

        headingJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headingJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingJLabel.setText("SIGN UP FORM");

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        RoleLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        RoleLabel.setText("Role:");
        RoleLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        RoleCombobox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        RoleCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Customer", "Investor" }));
        RoleCombobox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        nameJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nameJLabel.setText("Name:");
        nameJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        nameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        emailJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        emailJLabel.setText("Email ID:");
        emailJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        emailIdTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mobileNumJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        mobileNumJLabel.setText("Mobile Number:");
        mobileNumJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mobileNumTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mobileNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileNumTextFieldActionPerformed(evt);
            }
        });

        usernameJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        usernameJLabel.setText("Username:");
        usernameJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        usernameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        passwordJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        passwordJLabel.setText("Password:");
        passwordJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        passwordTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        signUpButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(headingJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(passwordJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 476, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoleCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(251, 251, 251))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(251, 251, 251)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mobileNumJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(usernameJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(9, 9, 9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usernameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(mobileNumTextField)
                                .addComponent(passwordTextField)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RoleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(emailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(251, 251, 251))
                .addGroup(layout.createSequentialGroup()
                    .addGap(345, 345, 345)
                    .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(RoleCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(passwordJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(148, 148, 148)
                    .addComponent(RoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(nameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mobileNumJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mobileNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usernameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        viewJPanel.removeAll();
        JPanel blankJP = new JPanel();
        viewJPanel.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) viewJPanel.getLayout();
        crdLyt.next(viewJPanel);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void mobileNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileNumTextFieldActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        try {
            name = nameTextField.getText();
            email = emailIdTextField.getText();
            username = usernameTextField.getText();
            password = passwordTextField.getText();
            mobileNumber = Long.parseLong(mobileNumTextField.getText());
            String role = RoleCombobox.getSelectedItem().toString();
            if (!RoleCombobox.getSelectedItem().toString().equals("--Select--") && !usernameTextField.getText().trim().isEmpty() && !passwordTextField.getText().trim().isEmpty() && !nameTextField.getText().trim().isEmpty() && !emailIdTextField.getText().trim().isEmpty() && !mobileNumTextField.getText().trim().isEmpty()) {
                if (!String.valueOf(mobileNumber).matches("[a-zA-Z]") && String.valueOf(mobileNumber).length() == 10 && String.valueOf(mobileNumber).matches("[0-9]+")) {
                    if (email.matches("^[a-zA-Z0-9_+&*-]+(?:\\." + "[a-zA-Z0-9_+&*-]+)*@" + "(?:[a-zA-Z0-9-]+\\.)+[a-z" + "A-Z]{2,7}$")) {
                        if (usernameTextField.getText().equals(passwordTextField.getText())) {
                            JOptionPane.showMessageDialog(null, "Username and password cannot be same");
                            usernameTextField.setText("");
                            passwordTextField.setText("");
                        } else {
                            for (Network network : business.getNetworkList()) {
                                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                                    if (enterprise.getUserAccountDirectory().checkIfUsernameIsUnique(username) == true) {
                                        if (role.equals("Customer")) {
                                            if (enterprise.getEnterpriseType().toString().equals("BitcoinMall")) {
                                                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                                    if (organization.toString().equals("Customer Organization")) {
                                                        mail();
                                                        Employee e = organization.getEmployeeDirectory().addEmployee(name, email, mobileNumber, Organization.Type.Customer);
                                                        UserAccount ua = organization.getUserAccountDirectory().createUserAccount(username, password, e, new CustomerRole());
                                                        JOptionPane.showMessageDialog(null, "Customer Created Succesfully");
                                                        Textfields();
                                                        viewJPanel.remove(this);
                                                        CardLayout layout = (CardLayout) viewJPanel.getLayout();
                                                        layout.previous(viewJPanel);
                                                    }
                                                }
                                            }
                                        } else {
                                            if (enterprise.getEnterpriseType().toString().equals("Exchange")) {
                                                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                                    if (organization.toString().equals("Investor Organization")) {
                                                        mail();
                                                        Employee e = organization.getEmployeeDirectory().addEmployee(name, email, mobileNumber, Organization.Type.Investor);
                                                        UserAccount ua = organization.getUserAccountDirectory().createUserAccount(username, password, e, new InvestorRole());
                                                        JOptionPane.showMessageDialog(null, "Investor Created Succesfully");
                                                        Textfields();
                                                        viewJPanel.remove(this);
                                                        CardLayout layout = (CardLayout) viewJPanel.getLayout();
                                                        layout.previous(viewJPanel);
                                                    }
                                                }
                                            }
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(null, "User already exists");
                                        usernameTextField.setText("");
                                    }
                                }
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please enter valid email address");
                        emailIdTextField.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please enter mobile number with 10 digits");
                    mobileNumTextField.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "All fields are madatory");
            }
        } catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(null, "Please enter valid number");
            mobileNumTextField.setText("");
        }
    }//GEN-LAST:event_signUpButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox RoleCombobox;
    private javax.swing.JLabel RoleLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField emailIdTextField;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JLabel mobileNumJLabel;
    private javax.swing.JTextField mobileNumTextField;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JButton signUpButton;
    private javax.swing.JLabel usernameJLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
