/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ExchangeEnterprise.MinerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Actor.Miner;
import Business.Organization.MinerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Niyati Maheshwari
 */
public class MinerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MinerWorkAreaPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private MinerOrganization minerOrganization;
    private Enterprise enterprise;
    private EcoSystem business;

    public MinerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, MinerOrganization minerOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.minerOrganization = minerOrganization;
        this.enterprise = enterprise;
        this.business = business;
        Miner miner = (Miner) account.getEmployee();
        btcJLabel.setText(String.valueOf(miner.getNoOfBitcoins()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        approvedTransBtn = new javax.swing.JButton();
        checkMempoolBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        walletBalanceJLabel = new javax.swing.JLabel();
        btcJLabel = new javax.swing.JLabel();

        approvedTransBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        approvedTransBtn.setText("Approved Transactions");
        approvedTransBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approvedTransBtnActionPerformed(evt);
            }
        });

        checkMempoolBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        checkMempoolBtn.setText("Check Mempool");
        checkMempoolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMempoolBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Miner's Dashboard");

        walletBalanceJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        walletBalanceJLabel.setText("Wallet Balance:");

        btcJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btcJLabel.setText("<Wallet Balance>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(approvedTransBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkMempoolBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(346, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(walletBalanceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btcJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(walletBalanceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(checkMempoolBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(approvedTransBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkMempoolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMempoolBtnActionPerformed
        // TODO add your handling code here:
        MempoolJPanel mempoolJPanel = new MempoolJPanel(userProcessContainer, userAccount, minerOrganization, enterprise, business);
        userProcessContainer.add("mempoolJPanel", mempoolJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_checkMempoolBtnActionPerformed

    private void approvedTransBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approvedTransBtnActionPerformed
        // TODO add your handling code here:
        MinerApprovalsJPanel minerApprovalsJPanel = new MinerApprovalsJPanel(userProcessContainer, userAccount, minerOrganization, enterprise, business);
        userProcessContainer.add("minerApprovalsJPanel", minerApprovalsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_approvedTransBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approvedTransBtn;
    private javax.swing.JLabel btcJLabel;
    private javax.swing.JButton checkMempoolBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel walletBalanceJLabel;
    // End of variables declaration//GEN-END:variables
}
