/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ExchangeEnterprise.InvertorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Actor.Investor;
import Business.Organization.CustodianOrganization;
import Business.Organization.InvestorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CustodianWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.LedgerJPanel;
import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Niyati Maheshwari
 */
public class InvestorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InvestorWorkAreaPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private InvestorOrganization investorOrganization;
    private Enterprise enterprise;
    private EcoSystem business;
    private boolean flag = false;

    public InvestorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, InvestorOrganization investorOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.investorOrganization = investorOrganization;
        this.enterprise = enterprise;
        this.business = business;
        walletIDValueLabel.setText(String.valueOf(userAccount.getEmployee().getWalletID()));
        Investor investor = (Investor) account.getEmployee();
        btcJLabel.setText(String.valueOf(investor.getNoOfBitcoins()));
        buyButton.setActionCommand("Buy");
        sellButton.setActionCommand("Sell");
        populateRequestTable();
        jPanel1.setVisible(false);
    }

    public void changeValue() {
        if (!btcTextField.getText().trim().isEmpty()) {
            try {
                double money = Double.parseDouble(btcTextField.getText()) * 9241.67;
                usdTextField.setText(String.valueOf(money));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Please enter valid data");
            }
        }else
            usdTextField.setText("");
    }

    public void populateRequestTable() {
        DefaultTableModel dtm = (DefaultTableModel) requestTable.getModel();
        dtm.setRowCount(0);

        for (WorkRequest request : userAccount.getWorkqueue().getWorkRequestList()) {
            Object[] row = new Object[5];
            row[0] = request.getRequestedDate();
            row[1] = ((CustodianWorkRequest) request).getRequestType();
            row[2] = request.getBitcoinsRequested();
            row[3] = request.getMessage();
            row[4] = request.getStatus();

            dtm.addRow(row);
        }
        requestTable.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 16));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroup = new javax.swing.ButtonGroup();
        walletBalanceJLabel = new javax.swing.JLabel();
        btcJLabel = new javax.swing.JLabel();
        balanceJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        tradeTypeJLabel = new javax.swing.JLabel();
        buyButton = new javax.swing.JRadioButton();
        sellButton = new javax.swing.JRadioButton();
        enterAmountJLabel = new javax.swing.JLabel();
        usdPriceJLabel = new javax.swing.JLabel();
        btcPriceJLabel = new javax.swing.JLabel();
        messageJLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        submitButton = new javax.swing.JButton();
        btcTextField = new javax.swing.JTextField();
        btcLabel = new javax.swing.JLabel();
        usdTextField = new javax.swing.JTextField();
        usdLabel = new javax.swing.JLabel();
        walletIDLabel = new javax.swing.JLabel();
        walletIDValueLabel = new javax.swing.JLabel();
        headingJLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        paymentLabel = new javax.swing.JLabel();
        walletIDLabel1 = new javax.swing.JLabel();
        walletIDLabel2 = new javax.swing.JLabel();
        walletIDLabel3 = new javax.swing.JLabel();
        walletIDLabel4 = new javax.swing.JLabel();
        cardNumbertxtfield = new javax.swing.JTextField();
        cvvTextField = new javax.swing.JTextField();
        nameTextfield = new javax.swing.JTextField();
        expiryTextfield = new javax.swing.JTextField();
        paymentLabel1 = new javax.swing.JLabel();
        amountlabel = new javax.swing.JLabel();
        payButton = new javax.swing.JButton();
        ledgerButton = new javax.swing.JButton();

        walletBalanceJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        walletBalanceJLabel.setText("Wallet Balance:");

        btcJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btcJLabel.setText("<Wallet Balance>");

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Buy/Sell", "Bitcoins", "Message", "Request Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestTable);

        tradeTypeJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tradeTypeJLabel.setText("Trade Type:");

        radioButtonGroup.add(buyButton);
        buyButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buyButton.setText("Buy");
        buyButton.setName(""); // NOI18N

        radioButtonGroup.add(sellButton);
        sellButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        sellButton.setText("Sell");
        sellButton.setName(""); // NOI18N
        sellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtonActionPerformed(evt);
            }
        });

        enterAmountJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        enterAmountJLabel.setText("Enter Amount:");

        usdPriceJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        messageJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        messageJLabel.setText("Message:");

        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        jScrollPane2.setViewportView(messageTextArea);

        submitButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        btcTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btcTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btcTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btcTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btcTextFieldKeyTyped(evt);
            }
        });

        btcLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btcLabel.setText("BTC");

        usdTextField.setEditable(false);
        usdTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        usdLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        usdLabel.setText("USD");

        walletIDLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        walletIDLabel.setText("Wallet ID:");

        walletIDValueLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        walletIDValueLabel.setText("<Wallet ID>");

        headingJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headingJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingJLabel.setText("Investor Work Area");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), java.awt.Color.gray));

        paymentLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        paymentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paymentLabel.setText("Payment");

        walletIDLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        walletIDLabel1.setText("Card Number:");

        walletIDLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        walletIDLabel2.setText("CVV:");

        walletIDLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        walletIDLabel3.setText("Name:");

        walletIDLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        walletIDLabel4.setText("Expiry:");

        cardNumbertxtfield.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        cvvTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cvvTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cvvTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cvvTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cvvTextFieldKeyTyped(evt);
            }
        });

        nameTextfield.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nameTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameTextfieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextfieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTextfieldKeyTyped(evt);
            }
        });

        expiryTextfield.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        expiryTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                expiryTextfieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                expiryTextfieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expiryTextfieldKeyTyped(evt);
            }
        });

        paymentLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        paymentLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paymentLabel1.setText("Pay:");

        amountlabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        amountlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountlabel.setText("<value>");

        payButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(walletIDLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expiryTextfield))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(walletIDLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cvvTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(walletIDLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(paymentLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(walletIDLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cardNumbertxtfield)
                            .addComponent(amountlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(walletIDLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumbertxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(walletIDLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(walletIDLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(walletIDLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ledgerButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ledgerButton.setText("Check Ledger");
        ledgerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ledgerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(balanceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tradeTypeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usdPriceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(messageJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enterAmountJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(sellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btcLabel)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(usdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(usdLabel))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ledgerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(103, 103, 103)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btcPriceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headingJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(walletIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(walletIDValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(walletBalanceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btcJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balanceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(walletIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(walletIDValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(walletBalanceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(btcPriceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tradeTypeJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(usdPriceJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enterAmountJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btcTextField)
                            .addComponent(btcLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ledgerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        if(!messageTextArea.getText().trim().isEmpty() && !btcTextField.getText().trim().isEmpty()){
        if (!buyButton.isSelected()) {
            String message = messageTextArea.getText();
            double bitcoins = Double.parseDouble(btcTextField.getText());
            if (bitcoins > Double.parseDouble(btcJLabel.getText())) {
                JOptionPane.showMessageDialog(null, "Your have insufficient balance to process this transaction.");
                return;
            }
            CustodianWorkRequest request = new CustodianWorkRequest();
            request.setMessage(message);
            request.setSender(userAccount);
            if (buyButton.isSelected()) {

                request.setRequestType("Buy");
            } else {
                request.setRequestType("Sell");
            }
            request.setBitcoinsRequested(bitcoins);
            request.setStatus("Pending");

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof CustodianOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkqueue().getWorkRequestList().add(request);
                userAccount.getWorkqueue().getWorkRequestList().add(request);
            }

            JOptionPane.showMessageDialog(null, "Request has been successfully submitted");
            populateRequestTable();
            radioButtonGroup.clearSelection();
            btcTextField.setText("");
            messageTextArea.setText("");
            usdTextField.setText("");
        } else {
            jPanel1.setVisible(true);
            amountlabel.setText("$ " + usdTextField.getText());
        }
        }else
            JOptionPane.showMessageDialog(null, "All fields are mandatory");
    }//GEN-LAST:event_submitButtonActionPerformed

    private void btcTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btcTextFieldKeyTyped

    }//GEN-LAST:event_btcTextFieldKeyTyped

    private void btcTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btcTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btcTextFieldKeyPressed

    private void sellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellButtonActionPerformed

    private void btcTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btcTextFieldKeyReleased
        // TODO add your handling code here:
        changeValue();
    }//GEN-LAST:event_btcTextFieldKeyReleased

    private void cvvTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvTextFieldKeyPressed

    private void cvvTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvTextFieldKeyReleased

    private void cvvTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvTextFieldKeyTyped

    private void nameTextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextfieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextfieldKeyPressed

    private void nameTextfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextfieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextfieldKeyReleased

    private void nameTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextfieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextfieldKeyTyped

    private void expiryTextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expiryTextfieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryTextfieldKeyPressed

    private void expiryTextfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expiryTextfieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryTextfieldKeyReleased

    private void expiryTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expiryTextfieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryTextfieldKeyTyped

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:
        if (!cardNumbertxtfield.getText().trim().isEmpty() && !cvvTextField.getText().trim().isEmpty() && !nameTextfield.getText().trim().isEmpty() && !expiryTextfield.getText().trim().isEmpty()) {
            String message = messageTextArea.getText();
            double bitcoins = Double.parseDouble(btcTextField.getText());
            CustodianWorkRequest request = new CustodianWorkRequest();
            request.setMessage(message);
            request.setSender(userAccount);
            if (buyButton.isSelected()) {

                request.setRequestType("Buy");
            } else {
                request.setRequestType("Sell");
            }
            request.setBitcoinsRequested(bitcoins);
            request.setStatus("Pending");

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof CustodianOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkqueue().getWorkRequestList().add(request);
                userAccount.getWorkqueue().getWorkRequestList().add(request);
            }

            populateRequestTable();
            JOptionPane.showMessageDialog(null, "Thank you for your payment! \nRequest has been successfully submitted");

            radioButtonGroup.clearSelection();
            btcTextField.setText("");
            messageTextArea.setText("");
            usdTextField.setText("");
            jPanel1.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "All fields are mandatory");
            return;
        }
    }//GEN-LAST:event_payButtonActionPerformed

    private void ledgerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ledgerButtonActionPerformed
        // TODO add your handling code here:
        LedgerJPanel ledgerJPanel = new LedgerJPanel(userProcessContainer, business);
        userProcessContainer.add("ledgerJPanel", ledgerJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ledgerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountlabel;
    private javax.swing.JLabel balanceJLabel;
    private javax.swing.JLabel btcJLabel;
    private javax.swing.JLabel btcLabel;
    private javax.swing.JLabel btcPriceJLabel;
    private javax.swing.JTextField btcTextField;
    private javax.swing.JRadioButton buyButton;
    private javax.swing.JTextField cardNumbertxtfield;
    private javax.swing.JTextField cvvTextField;
    private javax.swing.JLabel enterAmountJLabel;
    private javax.swing.JTextField expiryTextfield;
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton ledgerButton;
    private javax.swing.JLabel messageJLabel;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JTextField nameTextfield;
    private javax.swing.JButton payButton;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JLabel paymentLabel1;
    private javax.swing.ButtonGroup radioButtonGroup;
    private javax.swing.JTable requestTable;
    private javax.swing.JRadioButton sellButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel tradeTypeJLabel;
    private javax.swing.JLabel usdLabel;
    private javax.swing.JLabel usdPriceJLabel;
    private javax.swing.JTextField usdTextField;
    private javax.swing.JLabel walletBalanceJLabel;
    private javax.swing.JLabel walletIDLabel;
    private javax.swing.JLabel walletIDLabel1;
    private javax.swing.JLabel walletIDLabel2;
    private javax.swing.JLabel walletIDLabel3;
    private javax.swing.JLabel walletIDLabel4;
    private javax.swing.JLabel walletIDValueLabel;
    // End of variables declaration//GEN-END:variables
}
