/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.MallEnterprise.RetailerRole;

import Business.BookingHistory.Product;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Actor.Retailer;
import Business.Organization.RetailerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Niyati Maheshwari
 */
public class RetailerWorkAreaJPanel extends javax.swing.JPanel {
    /**
     * Creates new form RetailerWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private Retailer retailer;
    private RetailerOrganization retailerOrganization;
    private Enterprise enterprise;
    private EcoSystem business;
    private UserAccount account;
    
    public RetailerWorkAreaJPanel(JPanel userProcessContainer, Retailer retailer, RetailerOrganization retailerOrganization, Enterprise enterprise, EcoSystem business, UserAccount account) {
        initComponents(); //To change body of generated methods, choose Tools | Templates.
        this.userProcessContainer = userProcessContainer;
        this.retailer = retailer;
        this.retailerOrganization = retailerOrganization;
        this.enterprise= enterprise;
        this.business = business;
        this.account = account;
        Retailer retail = (Retailer) account.getEmployee();
        btcJLabel.setText(String.valueOf(retail.getNoOfBitcoins()));
        
        for(Product p : retailer.getProductCatalog().getProductCatalog()){
            System.out.println(p.getProductName() + " " +p.getProductCategory());
        }
    }
    
//    public RetailerWorkAreaJPanel(JPanel userProcessContainer, Retailer retailer, RetailerOrganization retailerOrganization, Enterprise enterprise) {
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingJLabel = new javax.swing.JLabel();
        manageProductButton = new javax.swing.JButton();
        claimMoneyButton = new javax.swing.JButton();
        checkRequestButton = new javax.swing.JButton();
        btcJLabel = new javax.swing.JLabel();
        walletBalanceJLabel = new javax.swing.JLabel();

        headingJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headingJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingJLabel.setText("Retailer Work Area");

        manageProductButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        manageProductButton.setText("Manage Product");
        manageProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductButtonActionPerformed(evt);
            }
        });

        claimMoneyButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        claimMoneyButton.setText("Claim your money");
        claimMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claimMoneyButtonActionPerformed(evt);
            }
        });

        checkRequestButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        checkRequestButton.setText("Check Request");
        checkRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRequestButtonActionPerformed(evt);
            }
        });

        btcJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btcJLabel.setText("<Wallet Balance>");

        walletBalanceJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        walletBalanceJLabel.setText("Wallet Balance:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headingJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(claimMoneyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(314, 314, 314))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(walletBalanceJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btcJLabel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(walletBalanceJLabel)
                    .addComponent(btcJLabel))
                .addGap(53, 53, 53)
                .addComponent(manageProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(claimMoneyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductButtonActionPerformed
        // TODO add your handling code here:
        ManageProductJPanel mpjpanel=new ManageProductJPanel(userProcessContainer, retailer.getProductCatalog());
        userProcessContainer.add("mpjpanel",mpjpanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageProductButtonActionPerformed

    private void claimMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claimMoneyButtonActionPerformed
        // TODO add your handling code here:
        RetailerWorkRequestJPanel rwjpanel=new RetailerWorkRequestJPanel(userProcessContainer,retailer, enterprise, account);
        userProcessContainer.add("rwjpanel",rwjpanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_claimMoneyButtonActionPerformed

    private void checkRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRequestButtonActionPerformed
        // TODO add your handling code here:
        RetailerRequestsJPanel rrqjpanel=new RetailerRequestsJPanel(userProcessContainer,retailer, enterprise, account);
        userProcessContainer.add("rrqjpanel",rrqjpanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);  
    }//GEN-LAST:event_checkRequestButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btcJLabel;
    private javax.swing.JButton checkRequestButton;
    private javax.swing.JButton claimMoneyButton;
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JButton manageProductButton;
    private javax.swing.JLabel walletBalanceJLabel;
    // End of variables declaration//GEN-END:variables
}
