/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.MallEnterprise.RetailerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Actor.Retailer;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MallAdminWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Niyati Maheshwari
 */
public class RetailerWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RetailerWorkArea
     */
    private JPanel userProcessContainer;
    private Retailer retailer;
    private Enterprise enterprise;
    private UserAccount account;

    public RetailerWorkRequestJPanel(JPanel userProcessContainer, Retailer retailer, Enterprise enterprise, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.retailer = retailer;
        this.enterprise = enterprise;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountJLabel = new javax.swing.JLabel();
        messageJLabel = new javax.swing.JLabel();
        messageTxtField = new javax.swing.JTextField();
        requestTxtField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        getRevenue = new javax.swing.JLabel();
        revenuelabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        amountJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        amountJLabel.setText("Amount:");

        messageJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        messageJLabel.setText("Message:");

        submitButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        getRevenue.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getRevenue.setForeground(new java.awt.Color(255, 0, 51));
        getRevenue.setText("Click here to know your today's revenue:");
        getRevenue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getRevenueMouseClicked(evt);
            }
        });

        revenuelabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        backButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(submitButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(getRevenue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(revenuelabel, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)))
                .addGap(240, 240, 240))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(amountJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(requestTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(messageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(messageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(revenuelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        if (retailer.getInvoiceRequest() == 0) {
            JOptionPane.showMessageDialog(null, "Your all transactions has been already settled");
        } else if (!requestTxtField.getText().trim().isEmpty() || !messageTxtField.getText().trim().isEmpty()) {
            if (!revenuelabel.getText().isEmpty()) {
                double value = Double.parseDouble(revenuelabel.getText());
                double money = Double.parseDouble(requestTxtField.getText());
                if (money > value) {
                    JOptionPane.showMessageDialog(null, "You cannot request more amount than your revenue");
                    return;
                }
                MallAdminWorkRequest request = new MallAdminWorkRequest();
                request.setMessage(messageTxtField.getText());
                
                request.setSender(account);
                request.setBitcoinsRequested(money);

                account.getWorkqueue().getWorkRequestList().add(request);

                for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()) {
                        if ("MallAdmin".equals(String.valueOf(ua.getEmployee().getType()))) {
                            ua.getWorkqueue().getWorkRequestList().add(request);
                            break;
                        }
                    }
                }
                retailer.setInvoiceMessage("Pending");
                JOptionPane.showMessageDialog(null, "Message Sent");
                messageTxtField.setText("");
                requestTxtField.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Please check your revenue first!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "All fields are mandatory");
        }

    }//GEN-LAST:event_submitButtonActionPerformed

    private void getRevenueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getRevenueMouseClicked
        // TODO add your handling code here:
        //double value;
        System.out.print(retailer.getInvoiceRequest());
        //value = retailer.getInvoiceRequest()- retailer.getInvoiceRequest()* (0.1 / 100);
        revenuelabel.setText(String.valueOf(retailer.getInvoiceRequest()));
    }//GEN-LAST:event_getRevenueMouseClicked

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountJLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel getRevenue;
    private javax.swing.JLabel messageJLabel;
    private javax.swing.JTextField messageTxtField;
    private javax.swing.JTextField requestTxtField;
    private javax.swing.JLabel revenuelabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
