/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.MallEnterprise.CustomerROle;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Actor.Customer;
import Business.Organization.CustomerOrganization;
import Business.UserAccount.UserAccount;
import UserInterface.LedgerJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Niyati Maheshwari
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkArea
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Customer customer;
    private CustomerOrganization customerOrganization;
    private Enterprise enterprise;
    private EcoSystem business;

    public CustomerWorkAreaJPanel(JPanel userProcessContainer, Customer customer, CustomerOrganization customerOrganization, Enterprise enterprise, EcoSystem business, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customer = customer;
        this.business = business;
        this.customerOrganization=customerOrganization;
        this.enterprise=enterprise;
        this.account = account;
        btcJLabel.setText(String.valueOf(customer.getNoOfBitcoins()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingJLabel = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox();
        goButton = new javax.swing.JButton();
        manageCartButton = new javax.swing.JButton();
        previousOrdersTracking = new javax.swing.JButton();
        walletBalanceJLabel = new javax.swing.JLabel();
        btcJLabel = new javax.swing.JLabel();
        myPaymentsbutton = new javax.swing.JButton();
        ledgerButton = new javax.swing.JButton();

        headingJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headingJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingJLabel.setText("Customer Work Area");

        categoryComboBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Category", "Clothing", "Electronics", "Food" }));

        goButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        goButton.setText("Go >>");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        manageCartButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        manageCartButton.setText("Manage your cart");
        manageCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCartButtonActionPerformed(evt);
            }
        });

        previousOrdersTracking.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        previousOrdersTracking.setText("Track Your Orders");
        previousOrdersTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousOrdersTrackingActionPerformed(evt);
            }
        });

        walletBalanceJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        walletBalanceJLabel.setText("Wallet Balance:");

        btcJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btcJLabel.setText("<Wallet Balance>");

        myPaymentsbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        myPaymentsbutton.setText("My Payments");
        myPaymentsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myPaymentsbuttonActionPerformed(evt);
            }
        });

        ledgerButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ledgerButton.setText("Check Ledger");
        ledgerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ledgerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(myPaymentsbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(manageCartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(previousOrdersTracking, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(ledgerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(walletBalanceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btcJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(walletBalanceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(manageCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(previousOrdersTracking, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myPaymentsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ledgerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
       if (categoryComboBox.getSelectedItem().toString().equals("Clothing")) {
            ClothingJPanel cjpanel = new ClothingJPanel(userProcessContainer, customer, business);
            userProcessContainer.add("cjpanel", cjpanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } 
       else if (categoryComboBox.getSelectedItem().toString().equals("Electronics")) {
            ElectronicsJPanel eJpanel = new ElectronicsJPanel(userProcessContainer, customer, business);
            userProcessContainer.add("ejpanel", eJpanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }else if(categoryComboBox.getSelectedItem().toString().equals("Food")) {
            FoodJPanel fJpanel = new FoodJPanel(userProcessContainer, customer, business);
            userProcessContainer.add("fjpanel", fJpanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }else
            JOptionPane.showMessageDialog(null,"Please select category first");
        
    }//GEN-LAST:event_goButtonActionPerformed

    private void manageCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCartButtonActionPerformed
//        // TODO add your handling code here:
        ManageCartJPanel mcjpanel = new ManageCartJPanel(userProcessContainer,customer.getOrderItem().getOrderItemList(), customer, enterprise, business, account);
        userProcessContainer.add("cjpanel", mcjpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCartButtonActionPerformed

    private void previousOrdersTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousOrdersTrackingActionPerformed
//        // TODO add your handling code here:
        TrackingDetailsJPanel tdjpanel = new TrackingDetailsJPanel(userProcessContainer, customer, customer.getOrderItem().getOrderItemList());
        userProcessContainer.add("tdjpanel", tdjpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_previousOrdersTrackingActionPerformed

    private void myPaymentsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myPaymentsbuttonActionPerformed
        // TODO add your handling code here:
        mypaymentsJpanel tdjpanel = new mypaymentsJpanel(userProcessContainer, account);
        userProcessContainer.add("tdjpanel", tdjpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_myPaymentsbuttonActionPerformed

    private void ledgerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ledgerButtonActionPerformed
        // TODO add your handling code here:
        LedgerJPanel ledgerJPanel = new LedgerJPanel(userProcessContainer, business);
        userProcessContainer.add("ledgerJPanel", ledgerJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ledgerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btcJLabel;
    private javax.swing.JComboBox categoryComboBox;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JButton ledgerButton;
    private javax.swing.JButton manageCartButton;
    private javax.swing.JButton myPaymentsbutton;
    private javax.swing.JButton previousOrdersTracking;
    private javax.swing.JLabel walletBalanceJLabel;
    // End of variables declaration//GEN-END:variables
}
